### ISSUE TITLE
10.7.5 Compatibility

### ISSUE THREAD

**Issue by dasginganinja** [marekhrabe/messenger#2]
This application gives me an error that says this application requires 10.8 or later. Any chance of adding this functionality?

**Comment by marekhrabe** [comment]
I think Messenger probably won't work on older systems than 10.8 as [Atom](https://atom.io/) (an app from GitHub that uses the same base as Messenger) only allows 10.8+ and they probably have reasons not to support it. I'm just using their code so the OS restriction needs to be same
