### ISSUE TITLE
On close, the app should minimize

### ISSUE THREAD

**Issue by kopiro** [marekhrabe/messenger#9]
When clicking the close button, the app should minimize in the dock, not closing.
Or, the app should really close, because clicking again in the dock will not show the app.

**Comment by marekhrabe** [comment]
Current behaviour is a bug that I introduced when I updated to custom window controls from native ones. I will fix that soon, thanks for the report

**Comment by anatolinicolae** [comment]
Check out one of my commits, I have fixed this annoying behaviour https://github.com/anatolinicolae/messenger/commit/1adb102db5f6b3eb7a4811aac44589b2717282d8
